apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: "" #create your db user
  POSTGRES_DB: "" #create db name
  POSTGRES_PASSWORD: "" # create password, base64 encoded
