apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  clusterIP: None  # Needed for StatefulSet stability
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432