apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "project.name" . }}-config
  labels:
    app: {{ .Values.commonLabels.app }}
    tier: {{ .Values.commonLabels.tier }}
{{- with .Values.config }}
data:
{{ toYaml . | nindent 2 }}
{{- end }}