apiVersion: v1
kind: Secret
metadata:
  name: {{ include "project.name" . }}-secret
  labels:
    app: {{ .Values.commonLabels.app }}
    tier: {{ .Values.commonLabels.tier }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD | b64enc | quote }}