apiVersion: v1
kind: Service
metadata:
  name: {{ include "project.name" . }}-svc
  labels:
    app: {{ .Values.commonLabels.app }}
    tier: {{ .Values.commonLabels.tier }}
spec:
  selector:
    app: {{ .Values.selectorLabels.app }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
